package br.com.ibm.cadeiabatch.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.UUID;

@DynamoDBTable(tableName = "usuario")
public class Usuario {

	private UUID id;
	
	private String nome;
	
	private String usuario;

	private String area;
	
	private String email;
	
	@JsonIgnore
	private String senha;


	
	public Usuario() {
		super();
	}
	public Usuario(UUID id, String nome, String usuario, String email, String senha) {
		super();
		this.id = id;
		this.nome = nome;
		this.usuario = usuario;
		this.email = email;
		this.senha = senha;
	}

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public UUID getId() {
		return id;
	}
	public void setId(UUID id) {
		this.id = id;
	}
	@DynamoDBAttribute(attributeName = "nome")
			public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	@DynamoDBAttribute(attributeName = "area")
			public String getArea() {
		return area;
	}
	public void setArea(String area) {
		this.area = area;
	}
	@DynamoDBAttribute(attributeName = "usuario")
			public String getUsuario() {
		return usuario;
	}
	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}
	@DynamoDBAttribute(attributeName = "email")
			public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	@DynamoDBAttribute(attributeName = "senha")
			public String getSenha() {
		return senha;
	}
	public void setSenha(String senha) {
		this.senha = senha;
	}

}
